name: tugasanalisis
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  calendar_appbar: ^0.0.6
  google_fonts: ^6.2.1
  fl_chart: ^0.70.2
  intl: ^0.17.0
  sqlite3_flutter_libs: ^0.5.29+1
  drift: ^2.24.0
  path_provider: ^2.1.5
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.24.0
  build_runner: ^2.4.14

flutter:
  uses-material-design: true
